/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.auth;

import BUS.AuthBUS;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Acer
 */
public class LoginGUI extends javax.swing.JFrame {

    private AuthBUS authBUS;

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        authBUS = new AuthBUS();
        startClock();
        setLocationRelativeTo(null);
        setSize(550, 500);
        setResizable(false);
        cHienMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHienMKActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel mainPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
                int w = getWidth();
                int h = getHeight();
                Color color1 = new Color(240, 242, 245);
                Color color2 = new Color(220, 230, 240);
                GradientPaint gp = new GradientPaint(0, 0, color1, 0, h, color2);
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, w, h);
            }
        };
        mainPanel.setLayout(new BorderLayout());

        // Create header panel with gradient styling (#1c92d2 -> #f2fcfe)
        JPanel headerPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
                int w = getWidth();
                int h = getHeight();
                Color color1 = new Color(0x1c92d2); // #1c92d2
                Color color2 = new Color(0xf2fcfe); // #f2fcfe
                GradientPaint gp = new GradientPaint(0, 0, color1, 0, h, color2);
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, w, h);
            }
        };
        headerPanel.setPreferredSize(new Dimension(550, 100));
        headerPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 25));

        lbTieuDe = new javax.swing.JLabel();
        lbTieuDe.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 28));
        lbTieuDe.setForeground(new Color(0xFFFF00)); // Bright yellow for prominence
        lbTieuDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotel.png")));
        lbTieuDe.setText("  QUẢN LÝ KHÁCH SẠN");
        headerPanel.add(lbTieuDe);

        // Create form panel with rounded border and shadow effect
        JPanel formPanel = new JPanel();
        formPanel.setBackground(Color.WHITE);
        formPanel.setBorder(BorderFactory.createCompoundBorder(
                new EmptyBorder(30, 40, 30, 40),
                BorderFactory.createLineBorder(new Color(220, 220, 220), 1, true)
        ));
        formPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Username field with modern styling
        lbTaiKhoan = new javax.swing.JLabel();
        lbTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person.png")));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        formPanel.add(lbTaiKhoan, gbc);

        tfTaiKhoan = new javax.swing.JTextField();
        tfTaiKhoan.setPreferredSize(new java.awt.Dimension(300, 40));
        tfTaiKhoan.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tfTaiKhoan.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200), 1, true),
                new EmptyBorder(5, 10, 5, 10)
        ));
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        formPanel.add(tfTaiKhoan, gbc);

        // Password field with modern styling
        lbMatKhau = new javax.swing.JLabel();
        lbMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/locked-computer.png")));
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        formPanel.add(lbMatKhau, gbc);

        pfMatKhau = new javax.swing.JPasswordField();
        pfMatKhau.setPreferredSize(new java.awt.Dimension(300, 40));
        pfMatKhau.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        pfMatKhau.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200), 1, true),
                new EmptyBorder(5, 10, 5, 10)
        ));
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        formPanel.add(pfMatKhau, gbc);

        // Show password checkbox with better styling
        cHienMK = new javax.swing.JCheckBox();
        cHienMK.setText("Hiện mật khẩu");
        cHienMK.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        cHienMK.setBackground(Color.WHITE);
        cHienMK.setForeground(new Color(100, 100, 100));
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        formPanel.add(cHienMK, gbc);

        // Button panel with modern styled buttons
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 0));
        buttonPanel.setBackground(Color.WHITE);

        btnQuenMK = new javax.swing.JButton();
        btnQuenMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png")));
        btnQuenMK.setText("Quên mật khẩu");
        btnQuenMK.setPreferredSize(new java.awt.Dimension(160, 40));
        btnQuenMK.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        btnQuenMK.setBackground(new Color(245, 245, 245));
        btnQuenMK.setForeground(new Color(80, 80, 80));
        btnQuenMK.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200), 1, true));
        btnQuenMK.setFocusPainted(false);
        btnQuenMK.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnQuenMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMKActionPerformed(evt);
            }
        });
        buttonPanel.add(btnQuenMK);

        btnDangNhap = new javax.swing.JButton();
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setPreferredSize(new java.awt.Dimension(140, 40));
        btnDangNhap.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnDangNhap.setBackground(new Color(41, 98, 255)); // Revert to original solid color
        btnDangNhap.setForeground(Color.WHITE);
        btnDangNhap.setBorder(BorderFactory.createEmptyBorder());
        btnDangNhap.setFocusPainted(false);
        btnDangNhap.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        buttonPanel.add(btnDangNhap);

        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.insets = new Insets(20, 10, 10, 10);
        formPanel.add(buttonPanel, gbc);

        // Clock label with modern styling
        lbThoiGian = new javax.swing.JLabel();
        lbThoiGian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThoiGian.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        lbThoiGian.setForeground(new Color(120, 120, 120));

        // Assemble main layout
        JPanel centerPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 40));
        centerPanel.setOpaque(false);
        centerPanel.add(formPanel);

        JPanel footerPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        footerPanel.setOpaque(false);
        footerPanel.add(lbThoiGian);

        mainPanel.add(headerPanel, BorderLayout.NORTH);
        mainPanel.add(centerPanel, BorderLayout.CENTER);
        mainPanel.add(footerPanel, BorderLayout.SOUTH);

        setContentPane(mainPanel);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startClock() {
        Timer timer = new Timer(1000, e -> {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            lbThoiGian.setText(sdf.format(new Date()));
        });
        timer.start();
    }

    // Method to handle show/hide password
    private void cHienMKActionPerformed(java.awt.event.ActionEvent evt) {
        if (cHienMK.isSelected()) {
            pfMatKhau.setEchoChar((char) 0); // Show password
        } else {
            pfMatKhau.setEchoChar('*'); // Hide password
        }
    }

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        String username = tfTaiKhoan.getText();
        String password = new String(pfMatKhau.getPassword());
        String message = authBUS.login(username, password);
        JOptionPane.showMessageDialog(this, message);
    }

    private void btnQuenMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-First:event_btnQuenMKActionPerformed
        ForgotPasswordGUI forgotPasswordDialog = new ForgotPasswordGUI(this);
        forgotPasswordDialog.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JCheckBox cHienMK;
    private javax.swing.JButton btnQuenMK;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTaiKhoan;
    private javax.swing.JLabel lbThoiGian;
    private javax.swing.JLabel lbTieuDe;
    private javax.swing.JPasswordField pfMatKhau;
    private javax.swing.JTextField tfTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
