/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.booking;

/**
 *
 * @author daoho
 */
public class BookingGUI extends javax.swing.JPanel {

    /**
     * Creates new form BookingGUI
     */
    public BookingGUI() {
        initComponents();
        initPopupMenu();
        jDialog1 = new javax.swing.JDialog((java.awt.Frame) null, "Bộ lọc tìm kiếm", true);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        tfTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnLoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatPhong = new javax.swing.JTable();
        cbTieuChi = new javax.swing.JComboBox<>();

        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        btnLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filter.png"))); // NOI18N
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        tbDatPhong.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, "231", null, "20/08/2025", "Trống", "Online", "Không"},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String [] {
                        "Mã đặt phòng", "Mã Phòng", "Mã khách hàng", "Ngày đặt", "Tình trạng", "Nguồn đặt ", "Ghi chú"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDatPhong);
        if (tbDatPhong.getColumnModel().getColumnCount() > 0) {
            tbDatPhong.getColumnModel().getColumn(0).setResizable(false);
            tbDatPhong.getColumnModel().getColumn(1).setResizable(false);
            tbDatPhong.getColumnModel().getColumn(2).setResizable(false);
            tbDatPhong.getColumnModel().getColumn(3).setResizable(false);
            tbDatPhong.getColumnModel().getColumn(4).setResizable(false);
            tbDatPhong.getColumnModel().getColumn(5).setResizable(false);
            tbDatPhong.getColumnModel().getColumn(6).setResizable(false);
        }

        cbTieuChi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã đặt phòng", "Mã phòng", "Mã khách hàng" }));
        cbTieuChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTieuChiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cbTieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initPopupMenu() {
        // Tạo menu item
        javax.swing.JMenuItem menuSua = new javax.swing.JMenuItem("Sửa");
        javax.swing.JMenuItem menuXoa = new javax.swing.JMenuItem("Xóa");
        javax.swing.JMenuItem menuDanhSachPhongDat = new javax.swing.JMenuItem("Danh sách phòng đặt");
        // Gắn vào popup
        jPopupMenu1.add(menuSua);
        jPopupMenu1.add(menuXoa);
        jPopupMenu1.add(menuDanhSachPhongDat);

        // Sự kiện "Sửa"
        menuSua.addActionListener(e -> suaDongDangChon());

        // Sự kiện "Xóa"
        menuXoa.addActionListener(e -> xoaDongDangChon());
        menuDanhSachPhongDat.addActionListener(e -> hienThiDanhSachPhongDat());

        // Thêm MouseListener cho JTable
        tbDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                showPopup(e);
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent e) {
                showPopup(e);
            }

            private void showPopup(java.awt.event.MouseEvent e) {
                if (e.isPopupTrigger()) { // chuột phải
                    int row = tbDatPhong.rowAtPoint(e.getPoint());
                    if (row >= 0 && row < tbDatPhong.getRowCount()) {
                        tbDatPhong.setRowSelectionInterval(row, row); // chọn đúng dòng click
                    } else {
                        tbDatPhong.clearSelection();
                    }
                    jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }


    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {
        // Hiện dialog khi bấm nút Lọc
        jDialog1.setTitle("Bộ lọc tìm kiếm");
        jDialog1.setSize(400, 300); // có thể chỉnh kích thước phù hợp
        jDialog1.setLocationRelativeTo(this); // canh giữa so với JPanel
        jDialog1.setModal(true); // chỉ cho phép thao tác trên dialog
        jDialog1.setVisible(true);
    }


    private void cbTieuChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTieuChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTieuChiActionPerformed

    private void suaDongDangChon() {
        int row = tbDatPhong.getSelectedRow();
        if (row != -1) {
            Object maDatPhong = tbDatPhong.getValueAt(row, 0);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Sửa dòng có Mã đặt phòng: " + maDatPhong);
            // TODO: Thêm code mở form sửa
        }
    }

    private void xoaDongDangChon() {
        int row = tbDatPhong.getSelectedRow();
        if (row != -1) {
            Object maDatPhong = tbDatPhong.getValueAt(row, 0);
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc muốn xóa Mã đặt phòng: " + maDatPhong + "?",
                    "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                ((javax.swing.table.DefaultTableModel) tbDatPhong.getModel()).removeRow(row);
            }
        }
    }

    private void hienThiDanhSachPhongDat() {
        int row = tbDatPhong.getSelectedRow();
        if (row != -1) {
            // Lấy mã đặt phòng từ dòng được chọn
            Object maDatPhong = tbDatPhong.getValueAt(row, 0);

            // Tạo và hiển thị cửa sổ BookingRoom
            BookingRoom bookingRoomFrame = new BookingRoom();
            bookingRoomFrame.setTitle("Danh sách phòng đặt - Mã: " + maDatPhong);
            bookingRoomFrame.setLocationRelativeTo(this);
            bookingRoomFrame.setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một dòng đặt phòng trước!",
                    "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbTieuChi;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDatPhong;
    private javax.swing.JTextField tfTimKiem;
    private javax.swing.JDialog jDialog1;
    // End of variables declaration//GEN-END:variables
}
