/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.billing.service;

import BUS.ServiceBUS;
import DTO.ServiceDTO;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
public class ServiceForm extends javax.swing.JFrame {
private final ServiceBUS serviceBus = new ServiceBUS();

    public ServiceForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý Dịch vụ");
        loadTableData();
    }

    private void loadTableData() {
        List<ServiceDTO> services = serviceBus.getAll();
        DefaultTableModel model = (DefaultTableModel) tblService.getModel();
        model.setRowCount(0);
        for (ServiceDTO s : services) {
            model.addRow(new Object[]{
                s.getServiceId(),
                s.getName(),
                s.getUnit(),
                s.getUnitPrice(),
                s.getChargeType(),
                s.isActive() ? "Hoạt động" : "Ngừng"
            });
        }
    }

   private void searchService() {
    String keyword = tfSearch.getText().trim().toLowerCase();
    String searchType = (String) CbserviceSearch.getSelectedItem();
    DefaultTableModel model = (DefaultTableModel) tblService.getModel();
    model.setRowCount(0);

    
    if (keyword.isEmpty()) {
        loadTableData();
        return;
    }

    List<ServiceDTO> allServices = serviceBus.getAll();
    List<ServiceDTO> results = new ArrayList<>();

    for (ServiceDTO s : allServices) {
        if (s == null) continue;

        switch (searchType) {
            case "Tên dịch vụ":
                if (s.getName() != null && s.getName().toLowerCase().contains(keyword)) {
                    results.add(s);
                }
                break;

            case "Đơn vị":
                if (s.getUnit() != null && s.getUnit().toLowerCase().contains(keyword)) {
                    results.add(s);
                }
                break;

            case "Giá":
                try {
                    double price = Double.parseDouble(keyword);
                    if (s.getUnitPrice() == price) {
                        results.add(s);
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Giá phải là số!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                break;
        }
    }

    
    if (results.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả phù hợp!");
        return;
    }

    
    for (ServiceDTO s : results) {
        model.addRow(new Object[]{
            s.getServiceId(),
            s.getName(),
            s.getUnit(),
            s.getUnitPrice(),
            s.getChargeType(),
            s.isActive() ? "Hoạt động" : "Ngừng"
        });
    }
}


private void addService() {
    
    ServiceDialog dialog = new ServiceDialog(this, true);
    ServiceDTO newService = dialog.openForCreate();

    if (newService != null) {
        
        serviceBus.add(newService);
        loadTableData();
        JOptionPane.showMessageDialog(this, "Thêm dịch vụ thành công!");
    }
}


private void editService() {
    int row = tblService.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ cần sửa!");
        return;
    }

    int id = (int) tblService.getValueAt(row, 0);
    ServiceDTO s = serviceBus.getById(id);

    ServiceDialog dialog = new ServiceDialog(this, true);
    ServiceDTO updated = dialog.openForEdit(s);

    if (updated != null) {
        serviceBus.update(updated);
        loadTableData();
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
    }
}



private void deleteService() {
    int row = tblService.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Chọn dịch vụ cần xóa!");
        return;
    }
    int id = (int) tblService.getValueAt(row, 0);
    int confirm = JOptionPane.showConfirmDialog(this, "Xóa dịch vụ này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        serviceBus.delete(id);
        loadTableData();
    }
}






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        CbserviceSearch = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTitle.setText("QUẢN LÝ DỊCH VỤ");

        tfSearch.setColumns(25);
        tfSearch.setToolTipText("");

        btnSearch.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên dịch vụ", "Đơn vị", "Giá", "Loại tính phí", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblService.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblService.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JScrollPane.setViewportView(tblService);

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        CbserviceSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên dịch vụ", "Đơn vị", "Giá", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(JScrollPane))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbserviceSearch, 0, 150, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnRefresh)
                    .addComponent(CbserviceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(33, 33, 33))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRefresh, btnSearch, tfSearch});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnDelete, btnEdit});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                     

                                 

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    loadTableData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    deleteService();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addService();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editService();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchService();
    }//GEN-LAST:event_btnSearchActionPerformed


   
  public static void main(String[] args) {
    javax.swing.SwingUtilities.invokeLater(() -> {
        new ServiceForm().setVisible(true);
    });
  }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbserviceSearch;
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblService;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
  
 
}
